### ISSUE TITLE
New Task: Create page for new novelty.

### ISSUE THREAD

**Issue by WidmarO** [WidmarO/tutoring-system-react#4]
Create a page `NewNovelty` into `pages` folder, I recommend create a form.
- Use  `NewAppointment.jsx` file like guide.

For both tasks use the prototypes in the [Testigos del bitcoin T2](https://github.com/WidmarO/Testigos-del-bitcoin-T2/tree/master/PrototiposMejorados) like guide.

**Comment by cristian1938** [comment]
**Task completed,** had trouble redirecting components
